# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  vaults3-linux-amd64 = {
    pname = "vaults3-linux-amd64";
    version = "4.4.49";
    src = fetchurl {
      url = "https://github.com/Kodiqa-Solutions/VaultS3/releases/download/v4.4.49/vaults3-linux-amd64.tar.gz";
      sha256 = "sha256-r8+WVJ2Ad7FjWH4lgNRfFlu9Dfz3wQ+9L4MlhAqCrp8=";
    };
  };
  vaults3-linux-arm64 = {
    pname = "vaults3-linux-arm64";
    version = "4.4.49";
    src = fetchurl {
      url = "https://github.com/Kodiqa-Solutions/VaultS3/releases/download/v4.4.49/vaults3-linux-arm64.tar.gz";
      sha256 = "sha256-1ln5YYEmfAsEbM9kkDHK2i41fK74SimRxMPLpUQRmjI=";
    };
  };
}
